on:
    push:
      branches:
        - main
    pull_request:

name: CI

jobs:
    lint:
        name: Lint
        runs-on: ubuntu-latest
        steps:
            - name: Checkout source code
              uses: actions/checkout@v6
            
            - name: Run clippy linter
              working-directory: post-quantum-client-testing
              run: cargo clippy -- -D warnings
    build:
        name: Build - ${{ matrix.platform.name }}
        needs: lint
        runs-on: ${{ matrix.platform.os }}
        strategy:
          matrix:
              platform:
                - name: linux-amd64
                  os: ubuntu-latest
                  target: x86_64-unknown-linux-gnu

                - name: linux-arm64
                  os: ubuntu-24.04-arm
                  target: aarch64-unknown-linux-gnu
                
                - name: macos-amd64
                  os: macos-15-intel
                  target: x86_64-apple-darwin

                - name: macos-arm64
                  os: macos-latest
                  target: aarch64-apple-darwin
                
                - name: windows-amd64
                  os: windows-latest
                  target: x86_64-pc-windows-msvc 
        steps:
          - name: Checkout source code
            uses: actions/checkout@v6
          
          - name: Install Linux dependencies
            if: runner.os == 'Linux'
            run: |
              sudo apt update
              sudo apt install -y build-essential pkg-config libclang-dev cmake libssl-dev
          
          - name: Install MacOS dependencies
            if: runner.os == 'macOS'
            run: |
              brew install openssl@3 cmake
              echo "OPENSSL_ROOT_DIR=$(brew --prefix openssl@3)" >> $GITHUB_ENV
              echo "PKG_CONFIG_PATH=$(brew --prefix openssl@3)/lib/pkgconfig" >> $GITHUB_ENV

          - name: Install Windows dependencies
            if: runner.os == 'Windows'
            run: |
              choco install cmake openssl -y
              echo "CARGO_TARGET_DIR=C:\t" >> $env:GITHUB_ENV
              echo "OPENSSL_DIR=C:\Program Files\OpenSSL" >> $env:GITHUB_ENV
              echo "OPENSSL_LIB_DIR=C:\Program Files\OpenSSL\lib\VC\x64\MT" >> $env:GITHUB_ENV
              echo "OPENSSL_INCLUDE_DIR=C:\Program Files\OpenSSL\include" >> $env:GITHUB_ENV
              echo "OPENSSL_STATIC=1" >> $env:GITHUB_ENV

          - name: Build the binary
            working-directory: post-quantum-client-testing
            run: |
              cargo build --release --target ${{ matrix.platform.target }}
