name: Create a release on tag
on:
    push:
        tags:
            - "v*.*.*"
jobs:
    build:
        name: Build - ${{ matrix.platform.name }}
        runs-on: ${{ matrix.platform.os }}
        permissions:
            contents: write
        env:
            GH_TOKEN: ${{ github.token }}
            SERVICE_ACCOUNT_JSON: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
        strategy:
          matrix:
              platform:
                - name: linux-amd64
                  os: ubuntu-latest
                  target: x86_64-unknown-linux-gnu
                
                - name: linux-arm64
                  os: ubuntu-24.04-arm
                  target: aarch64-unknown-linux-gnu

                - name: macos-amd64
                  os: macos-15-intel
                  target: x86_64-apple-darwin

                - name: macos-arm64
                  os: macos-latest
                  target: aarch64-apple-darwin

                - name: windows-amd64
                  os: windows-latest
                  target: x86_64-pc-windows-msvc
        steps:
            - name: Checkout source code
              uses: actions/checkout@v6
              with:
                fetch-depth: 0

            - name: Install Linux dependencies
              if: runner.os == 'Linux'
              run: |
                sudo apt update
                sudo apt install -y build-essential pkg-config libclang-dev cmake libssl-dev

            - name: Install MacOS dependencies
              if: runner.os == 'macOS'
              run: |
                brew install openssl@3 cmake
                echo "OPENSSL_ROOT_DIR=$(brew --prefix openssl@3)" >> $GITHUB_ENV
                echo "PKG_CONFIG_PATH=$(brew --prefix openssl@3)/lib/pkgconfig" >> $GITHUB_ENV

            - name: Install Windows dependencies
              if: runner.os == 'Windows'
              run: |
                choco install cmake openssl -y
                echo "CARGO_TARGET_DIR=C:\t" >> $env:GITHUB_ENV
                echo "OPENSSL_DIR=C:\Program Files\OpenSSL" >> $env:GITHUB_ENV
                echo "OPENSSL_LIB_DIR=C:\Program Files\OpenSSL\lib\VC\x64\MT" >> $env:GITHUB_ENV
                echo "OPENSSL_INCLUDE_DIR=C:\Program Files\OpenSSL\include" >> $env:GITHUB_ENV
                echo "OPENSSL_STATIC=1" >> $env:GITHUB_ENV
            
            - name: Build the binary
              working-directory: post-quantum-client-testing
              run: |
                cargo build --release --target ${{ matrix.platform.target }}

            - name: Create release if one doesn't exist yet
              shell: bash
              run: |
                EXISTING_RELEASE=$(gh release view $GITHUB_REF_NAME --json="id" || echo '')
                if [[ -z $EXISTING_RELEASE ]]; then
                    gh release create $GITHUB_REF_NAME --generate-notes
                fi
            
            - name: Upload built binary to release
              shell: bash
              run: |
               if [[ "${{ runner.os }}" == "Windows" ]]; then
                    binary="C:/t/${{ matrix.platform.target }}/release/post-quantum-client-testing.exe"
                    filename="post-quantum-client-testing-${{ matrix.platform.name }}.zip"
                    7z a "$filename" "$binary"
                    gh release upload $GITHUB_REF_NAME "$filename" --clobber
                else
                    binary="post-quantum-client-testing/target/${{ matrix.platform.target }}/release/post-quantum-client-testing"
                    filename="post-quantum-client-testing-${{ matrix.platform.name }}.zip"
                    zip -j "$filename" "$binary"
                    gh release upload $GITHUB_REF_NAME "$filename" --clobber
                fi
